baseurl = "law2019.netlify.com"
title = "Social Science Methodology"
author = "JinLIN@NUFE"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Social Science Methodology"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "law2019.netlify.com"
[[menu.main]]
    name = "Projects"
    url  = "law2019.netlify.com"
[[menu.main]]
    name = "Resume"
    url  = "law2019.netlify.com"

