baseurl = "/"
title = "Social Science Methodology"
author = "JinLIN@NUFE"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Social Science Methodology"
  disableWebFonts = false

[[menu.main]]
    name = "Main"
    url  = "/"
[[menu.main]]
    name = "Projects"
    url  = "/projects/"

